// Generated by CoffeeScript 1.6.3
var Converter, ConverterMethods;

ConverterMethods = {
  int: function(value) {
    return ConverterMethods.float(value);
  },
  float: function(value) {
    return parseFloat(value);
  }
};

module.exports = Converter = {
  convert: function(types, data) {
    var field, value;
    for (field in types) {
      value = types[field];
      value = data[field];
      if (value) {
        data[field] = this.convertField(value, types[field].type);
      }
    }
    return data;
  },
  convertField: function(value, type) {
    if (ConverterMethods[type]) {
      return ConverterMethods[type](value);
    } else {
      return value;
    }
  },
  registerConverter: function(name, converter) {
    return ConverterMethods[name] = converter;
  }
};
