// Generated by CoffeeScript 1.6.3
var ControllerManager, FrontEnd, FuncDetails;

FuncDetails = require('./func-details');

ControllerManager = require('./manager');

module.exports = FrontEnd = {
  registerRoutes: function(app) {
    var controller, _i, _len, _ref;
    _ref = ControllerManager.controllers;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      controller = _ref[_i];
      controller.registerRoutes(app);
    }
    return app.get('/js/lib/ez-routes.js', function(req, res) {
      var frontEndJS;
      frontEndJS = FrontEnd.getFrontEndMethods();
      return res.end(frontEndJS);
    });
  },
  getFrontEndMethods: function() {
    var ZController, argString, controller, controllerDetails, funcDetails, funcName, funcString, routes, _i, _len;
    routes = ControllerManager.getAllRoutes();
    ZController = {};
    for (controllerDetails = _i = 0, _len = routes.length; _i < _len; controllerDetails = ++_i) {
      controller = routes[controllerDetails];
      EZController._makeRequest = function(routeDetails, args) {};
      EZController[controller] = {};
      EZController[controller]._routeDetails = {};
      for (funcDetails in controllerDetails) {
        funcName = controllerDetails[funcDetails];
        EZController[controller]._routeDetails[funcName] = {
          pattern: funcDetails.pattern,
          usesId: funcDetails.usesId,
          method: funcDetails.method
        };
        argString = FuncDetails.extractArgumentString(funcDetails.logic);
        funcString = "function logic(" + argString + ") {\n" + "	EZController._makeRequest(this._routeDetails['" + funcName + "'], arguments);\n" + "};";
        EZController[controller][funcName] = eval(funcString);
      }
    }
    return EZController.toString();
  }
};
