// Generated by CoffeeScript 1.6.3
(function() {
  var FuncDetails, _;

  _ = require('underscore');

  module.exports = FuncDetails = {
    extractArguments: function(fn) {
      var FN_ARG, FN_ARGS, FN_ARG_SPLIT, STRIP_COMMENTS, arg, argDecl, argsList, fnText, _i, _len, _ref;
      FN_ARGS = /^function\s*[^\(]*\(\s*([^\)]*)\)/m;
      FN_ARG_SPLIT = /,/;
      FN_ARG = /^\s*(_?)(\S+?)\1\s*$/;
      STRIP_COMMENTS = /((\/\/.*$)|(\/\*[\s\S]*?\*\/))/mg;
      if (_.isFunction(fn)) {
        if (!(argsList = fn.argsList)) {
          argsList = [];
          fnText = fn.toString().replace(STRIP_COMMENTS, '');
          argDecl = fnText.match(FN_ARGS);
          _ref = argDecl[1].split(FN_ARG_SPLIT);
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            arg = _ref[_i];
            arg.replace(FN_ARG, function(all, underscore, name) {
              return argsList.push(name);
            });
          }
          fn.argsList = argsList;
        }
        return argsList;
      } else {
        return null;
      }
    },
    dataToArgs: function(fn, data) {
      var arg, argData, args, i, unseenData, _dataPosition;
      args = FuncDetails.extractArguments(fn);
      argData = [];
      unseenData = _.extend({}, data);
      argData = (function() {
        var _i, _len, _ref, _results;
        _ref = args || [];
        _results = [];
        for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
          arg = _ref[i];
          if (arg === "_data") {
            _dataPosition = i;
            _results.push(null);
          } else {
            delete unseenData[arg];
            _results.push(data[arg]);
          }
        }
        return _results;
      })();
      if (_dataPosition != null) {
        argData[_dataPosition] = unseenData;
      }
      return argData;
    },
    argsToData: function(argList, args) {
      var argString, data, field, i, value, _i, _len, _ref, _ref1;
      data = {};
      _ref = argList || [];
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        argString = _ref[i];
        if (argString === "_data") {
          _ref1 = args[i];
          for (value in _ref1) {
            field = _ref1[value];
            data[field] = value;
          }
        } else {
          data[argString] = args[i];
        }
      }
      return data;
    },
    extractArgumentString: function(fn) {
      var FN_ARGS;
      FN_ARGS = /^function\s*[^\(]*\(\s*([^\)]*)\)/m;
      return fn.toString().match(FN_ARGS)[1].replace(/\r/g, "");
    }
  };

}).call(this);
