// Generated by CoffeeScript 1.6.3
var _;

_ = require('underscore');

module.exports = {
  controllers: [],
  getAllRoutes: function() {
    return _.reduce(this.controllers, function(memo, controller) {
      if (controller.modelName) {
        memo[controller.modelName] = controller.getRoutes();
      }
      return memo;
    }, {});
  }
};
