// Generated by CoffeeScript 1.6.3
var FrontEnd, TestData, app, express, http;

express = require('express');

http = require('http');

FrontEnd = require('../index').FrontEnd;

app = express();

app.use(express.json());

app.use(express.urlencoded());

app.use(express.bodyParser());

app.use(express["static"](__dirname + "/server_public"));

TestData = require('./data');

FrontEnd.registerRoutes(app);

module.exports = {
  start: function(cb) {
    if (!cb) {
      cb = function() {};
    }
    this.server = http.createServer(app);
    return this.server.listen(3000, cb);
  },
  close: function(cb) {
    if (!cb) {
      cb = function() {};
    }
    return this.server.close(cb);
  }
};
