// Generated by CoffeeScript 1.8.0
(function() {
  var app, express, frontEnd, http, wait;

  express = require('express');

  http = require('http');

  frontEnd = new (require('../index').FrontEnd)();

  app = express();

  app.use(express.json());

  app.use(express.urlencoded());

  app.use(express.bodyParser());

  app.use(express["static"](__dirname + "/server_public"));

  wait = frontEnd.registerRoutes(app, __dirname + "/routes", true)["catch"](function(error) {
    return console.log('FAIL', error, error != null ? error.stack : void 0);
  });

  module.exports = {
    start: function(cb) {
      if (!cb) {
        cb = function() {};
      }
      this.server = http.createServer(app);
      return wait.then((function(_this) {
        return function() {
          return _this.server.listen(3000, cb);
        };
      })(this));
    },
    close: function(cb) {
      if (!cb) {
        cb = function() {};
      }
      return this.server.close(cb);
    }
  };

}).call(this);
