// Generated by CoffeeScript 1.6.3
(function() {
  var BaseController, ErrorHandler, MyBaseController, Q, UserData, base, data, middleware;

  Q = require('q');

  base = require('../../index');

  BaseController = base.BaseController;

  data = require('../data');

  middleware = data.middleware;

  UserData = data.Userdata;

  ErrorHandler = data.ErrorHandler;

  module.exports = MyBaseController = BaseController.extend({
    isAbstract: true,
    beforeEach: function(req, res, next) {
      middleware.myBaseRan++;
      return next();
    }
  });

  MyBaseController.prototype.logError = function(error) {
    return ErrorHandler.logError(error);
  };

}).call(this);
