// Generated by CoffeeScript 1.8.0
(function() {
  var BaseController, ErrorHandler, MyBaseController, UserData, base, beforeEach, data, middleware;

  base = require('../../index');

  BaseController = base.BaseController;

  data = require('../data');

  middleware = data.middleware;

  beforeEach = data.beforeEach;

  UserData = data.Userdata;

  ErrorHandler = data.ErrorHandler;

  module.exports = MyBaseController = BaseController.extend({
    isAbstract: true,
    beforeEach: function() {
      return beforeEach.myBaseRan++;
    },
    middleware: function(req, res, next) {
      middleware.myBaseRan++;
      return next();
    }
  });

  MyBaseController.prototype.logError = function(error) {
    return ErrorHandler.logError(error);
  };

}).call(this);
